# a=open("futura.txt","x")       to create a file
# a=open("futura.txt","w")
# a.write("welcome")
# a.close()
b=open("futura.txt","r")
c=b.read()
print(c)
b.close()
# a=open("futura01.txt","x")
# a=open("futura01.txt","w")
# a.write(" to futuralabs")
# a.close()
a=open("futura01.txt","r")
d=a.read()
print(d)
a.close()
# a=open("futuralabs.txt","x")
# a=open("futuralabs.txt","w")
# e=a.write(c+d)v
# a.close
a=open("futuralabs.txt","r")
f=a.read()
print(f)
a.close()